# Este es el makefile de IUTS_matrixmod
# 
# gcc -fopenmp ../Librerias_usuario/matrices.c ../Librerias_usuario/libMatrixmodG.c -o IUTS_matrixmod.out

#VARIABLES

#REGLAS
make:
	gcc -fopenmp ../Librerias_usuario/MV_object.c ../Librerias_usuario/libMatrixmodG.c ./Pruebas_Sistema/system_tests.c IUTS_matrixmod.c -o IUTS_matrixmod.out	
clean:
	rm -rf *.out
	rm -rf *~
