# Makefile de APP C++
# 
# gcc -fopenmp ../Librerias_usuario/matrices.c ../Librerias_usuario/libMatrixmodG.c -o IUTS_matrixmod.out

#VARIABLES

#REGLAS
make:
	g++ monitor.cpp -o monitor.out -pthread -std=c++0x	
clean:
	rm -rf *.out
	rm -rf *~
